### ISSUE TITLE
Crash when selecting encounter

### ISSUE THREAD

**Issue by Banshee786** [PyrexPi/prophet#1]
```
PS C:\Users\kylem\Desktop\prophet> .\prophet.exe
Id  0  -  Microsoft Sound Mapper - Input
Id  1  -  Alesis Multimix 4 (USB Audio CO
Id  2  -  Headset Microphone (4- Arctis P
Id  3  -  Headset Microphone (Oculus Virt
Id  4  -  Microphone (Voicemod Virtual Au
Id  5  -  Microphone (Steam Streaming Mic
Id  6  -  Microsoft Sound Mapper - Output
Id  7  -  Headphones (4- Arctis Pro Wirel
Id  8  -  1 - Optix MAG27CQ (AMD High Def
Id  9  -  Speakers (Steam Streaming Micro
Id  10  -  Line (Voicemod Virtual Audio De
Id  11  -  Headphones (Oculus Virtual Audi
Id  12  -  Headset Earphone (4- Arctis Pro
Id  13  -  Speakers (Steam Streaming Speak
Id  14  -  Speakers (USB Audio CODEC )
Choose your virtual device: 7
Do you want to keep your preferred device (delete device.txt to reset preferences) y/n: n
Choose your encounter file (templar/atheon): templar
Traceback (most recent call last):
  File "main.py", line 54, in <module>
  File "pyaudio.py", line 750, in open
  File "pyaudio.py", line 441, in __init__
OSError: [Errno -9998] Invalid number of channels
[10940] Failed to execute script main```

**Comment by PyrexPi** [comment]
You have selected your headphones. You need to route the game's audio through a virtual input like VB-Cable. If you still have trouble follow the guide on the [readme](https://github.com/PyrexPi/prophet/blob/main/README.md) and report back. Thanks!

**Comment by PyrexPi** [comment]
I'mkclosing this because it's been 2 days and never reported back, so I think they've fixed the problem. If not, feel free to open a new issue.
